import Head from 'next/head'

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl text-center">
        Dashboard
      </div>
    </div>
  )
}
