import Head from 'next/head';

export default function Home() {
  return (
    <div className="min-h-screen bg-[#EEEEEE]">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <div className="p-14 bg-[#1C64F2]">
          
        </div>

        <div className="p-3">
            
        </div>

        <div className="flex justify-center gap-3">
          <div className="p-20 max-w-[50%] bg-white rounded shadow-md">
            Date and Time
          </div>

          <div>

          </div>
         
          <div className="p-20 max-w-sm bg-white rounded shadow-md">
           Connection Graph
          </div>
        </div>

        <div className="p-3">
            
        </div>

        {/* <div class="flex justify-center">
          <div class="p-20 max-w-sm bg-white rounded shadow-md">
            Data and Time
          </div>
        </div> */}

        <div className="p-3">
            
        </div>

        


      </div>
    </div>
  )
}
