import Head from 'next/head'
import { Navbar } from "flowbite-react";


export default function Home() {
  return (
    <div className="min-h-screen bg-[#EEEEEE]">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Navbar
          fluid={true}
          rounded={true}
        >
          <Navbar.Brand href="https://flowbite.com/">
            <img
              src="https://flowbite.com/docs/images/logo.svg"
              className="mr-3 h-6 sm:h-9"
              alt="Flowbite Logo"
            />
            <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
              LAN-SECURE 
            </span>
          </Navbar.Brand>
          
          <Navbar.Toggle />
          <Navbar.Collapse>
            <Navbar.Link
              href="/navbars">
              Dashboard
            </Navbar.Link>
            <Navbar.Link href="/navbars">
              About
            </Navbar.Link>
            <Navbar.Link href="/navbars">
              Record
            </Navbar.Link>
          </Navbar.Collapse>
        </Navbar>

        
        <div class="p-14 bg-[#1C64F2]">
          
        </div>

        <div class="p-3">
            
        </div>

        <div class="flex justify-center gap-3">
          <div class="p-20 max-w-[50%] bg-white rounded shadow-md">
            Date and Time
          </div>

          <div>

          </div>
         
          <div class="p-20 max-w-sm bg-white rounded shadow-md">
           Connection Graph
          </div>
        </div>

        <div class="p-3">
            
        </div>

        {/* <div class="flex justify-center">
          <div class="p-20 max-w-sm bg-white rounded shadow-md">
            Data and Time
          </div>
        </div> */}

        <div class="p-3">
            
        </div>

        


      </div>
    </div>
  )
}
